start restructuring work
DoubleYouGTT/hubspot pull request #39
Opened 2019-11-04 09:37 UTC by maelle

2019-11-04 12:25 UTC, maelle commented
Goals = having a good code structure for the current functions, before adding others.

Tackles
#11 (a bit)
#1 
#30

2019-11-04 13:43 UTC, maelle commented on .gitattributes
> +tests/fixtures/**/* -diff
see https://github.com/ropensci/vcr/issues/109

2019-11-04 13:43 UTC, maelle commented on .travis.yml
> +      - libsodium-dev
Needed for keyring

2019-11-04 14:40 UTC, maelle commented
The failure on Mac is a LaTeX error :scream: :see_no_evil:

2019-11-12 15:25 UTC, stephlocke commented
A NOTE in travis
>hubspot_key_get: no visible global function definition for ‘is’
Undefined global functions or variables:
  is
Consider adding
  importFrom("methods", "is")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').

Will review properly tomorrow probably. For now I've looked through all the files and things seem fine. I just want to trial the user experience :)

2019-11-14 16:20 UTC, maelle commented
Hopefully the user experience didn't change! Do you think you'll have reviewed this before Monday? :-)

2019-11-15 11:45 UTC, stephlocke requested changes
Can you add the new set function to the example(s) in the README? Can still set to the value of demo

2019-11-15 12:22 UTC, maelle commented
before you can review?

2019-11-15 15:02 UTC, stephlocke commented
> before you can review?

nope, done my review and happy for the changes, just want to keep the docs in sync for when we merge in

2019-11-15 15:50 UTC, maelle commented
Ok! Thanks!

2019-11-18 09:39 UTC, merged